"""List of companies to track.

group: top | boutique | bank | academic
type:  one of scraper.fetchers.FETCHERS
Fields like slug / site accept a list of candidates; the first working one is used.
"""

Q_BROAD = ["intern", "security", "research"]

SOURCES = [
    # ----------------------------------------------------------------- Top tech
    {"company": "Google", "group": "top", "type": "google", "queries": ["intern", "security intern", "research intern", "PhD"]},
    {"company": "Google DeepMind", "group": "top", "type": "google", "queries": ["DeepMind intern", "student researcher"]},
    {"company": "Microsoft", "group": "top", "type": "microsoft", "queries": ["intern", "security intern", "research intern", "PhD"]},
    {"company": "Microsoft Research", "group": "top", "type": "page_scan",
     "url": ["https://www.microsoft.com/en-us/research/academic-program/phd-internship/",
             "https://www.microsoft.com/en-us/research/careers/"]},
    {"company": "Meta", "group": "top", "type": "meta", "queries": ["intern", "security intern", "research scientist intern"]},
    {"company": "Amazon", "group": "top", "type": "amazon", "queries": ["intern", "security intern", "applied science intern", "PhD"]},
    {"company": "Apple", "group": "top", "type": "apple", "queries": ["intern", "security intern", "PhD"]},
    {"company": "NVIDIA", "group": "top", "type": "workday", "host": "nvidia.wd5.myworkdayjobs.com",
     "tenant": "nvidia", "site": ["NVIDIAExternalCareerSite"], "queries": ["intern", "security intern", "PhD"]},
    {"company": "Intel", "group": "top", "type": "workday", "host": "intel.wd1.myworkdayjobs.com",
     "tenant": "intel", "site": ["External"], "queries": ["intern", "security intern", "PhD"]},
    {"company": "AMD", "group": "top", "type": "workday", "host": "amd.wd1.myworkdayjobs.com",
     "tenant": "amd", "site": [], "queries": ["intern", "security"]},
    {"company": "Qualcomm", "group": "top", "type": "workday", "host": "qualcomm.wd5.myworkdayjobs.com",
     "tenant": "qualcomm", "site": [], "queries": ["intern", "security"]},
    {"company": "Arm", "group": "top", "type": "workday", "host": "arm.wd3.myworkdayjobs.com",
     "tenant": "arm", "site": [], "queries": ["intern", "security"]},
    {"company": "IBM", "group": "top", "type": "ibm", "queries": ["intern", "security intern", "research intern"]},
    {"company": "IBM Research", "group": "top", "type": "page_scan",
     "url": ["https://research.ibm.com/careers", "https://www.zurich.ibm.com/careers/"]},
    {"company": "Cisco", "group": "top", "type": "cisco", "queries": ["intern", "security intern"]},
    {"company": "Salesforce", "group": "top", "type": "workday", "host": "salesforce.wd12.myworkdayjobs.com",
     "tenant": "salesforce", "site": ["External_Career_Site"], "queries": ["intern", "security intern"]},
    {"company": "Anthropic", "group": "top", "type": "greenhouse", "slug": ["anthropic"]},
    {"company": "OpenAI", "group": "top", "type": "ashby", "slug": ["openai"]},
    {"company": "xAI", "group": "top", "type": "greenhouse", "slug": ["xai"]},
    {"company": "Mistral AI", "group": "top", "type": "lever", "slug": ["mistral"]},
    {"company": "SpaceX", "group": "top", "type": "greenhouse", "slug": ["spacex"]},
    {"company": "Tesla", "group": "top", "type": "tesla"},
    {"company": "Palantir", "group": "top", "type": "lever", "slug": ["palantir"]},
    {"company": "Databricks", "group": "top", "type": "greenhouse", "slug": ["databricks"]},
    {"company": "Cloudflare", "group": "top", "type": "greenhouse", "slug": ["cloudflare"]},
    {"company": "GitHub", "group": "top", "type": "page_scan", "url": ["https://www.github.careers/careers-home/jobs?keywords=intern"]},
    {"company": "GitLab", "group": "top", "type": "greenhouse", "slug": ["gitlab"]},
    {"company": "Mozilla", "group": "top", "type": "greenhouse", "slug": ["mozilla"]},
    {"company": "Netflix", "group": "top", "type": "eightfold", "host": "explore.jobs.netflix.net",
     "domain": "netflix.com", "queries": ["intern", "security"]},
    {"company": "Airbnb", "group": "top", "type": "greenhouse", "slug": ["airbnb"]},
    {"company": "Dropbox", "group": "top", "type": "greenhouse", "slug": ["dropbox"]},
    {"company": "Discord", "group": "top", "type": "greenhouse", "slug": ["discord"]},
    {"company": "Roblox", "group": "top", "type": "greenhouse", "slug": ["roblox"]},
    {"company": "Reddit", "group": "top", "type": "greenhouse", "slug": ["reddit"]},
    {"company": "Twilio", "group": "top", "type": "greenhouse", "slug": ["twilio"]},
    {"company": "Figma", "group": "top", "type": "greenhouse", "slug": ["figma"]},
    {"company": "Datadog", "group": "top", "type": "greenhouse", "slug": ["datadog"]},
    {"company": "Elastic", "group": "top", "type": "greenhouse", "slug": ["elastic"]},
        {"company": "Okta", "group": "top", "type": "greenhouse", "slug": ["okta"]},
    {"company": "Samsara", "group": "top", "type": "greenhouse", "slug": ["samsara"]},
        {"company": "Uber", "group": "top", "type": "page_scan", "url": ["https://www.uber.com/us/en/careers/list/?query=intern"]},
    {"company": "Stripe", "group": "top", "type": "greenhouse", "slug": ["stripe"]},
    {"company": "Coinbase", "group": "top", "type": "greenhouse", "slug": ["coinbase"]},
    {"company": "Robinhood", "group": "top", "type": "greenhouse", "slug": ["robinhood"]},
    {"company": "Plaid", "group": "top", "type": "ats_any", "candidates": [{"type": "greenhouse", "slug": "plaid"}, {"type": "ashby", "slug": "plaid"}, {"type": "lever", "slug": "plaid"}]},
    {"company": "Brex", "group": "top", "type": "greenhouse", "slug": ["brex"]},
    {"company": "Ramp", "group": "top", "type": "ashby", "slug": ["ramp"]},
    {"company": "Proton", "group": "top", "type": "greenhouse", "slug": ["proton", "protonag"]},
    {"company": "1Password", "group": "top", "type": "ats_any", "candidates": [{"type": "greenhouse", "slug": "1password"}, {"type": "ashby", "slug": "1password"}, {"type": "lever", "slug": "agilebits"}]},
    {"company": "Chainalysis", "group": "top", "type": "ats_any", "candidates": [{"type": "lever", "slug": "chainalysis"}, {"type": "greenhouse", "slug": "chainalysiscareers"}, {"type": "ashby", "slug": "chainalysis"}]},

    # ----------------------------------------------------- Boutique / security firms
    {"company": "Trail of Bits", "group": "boutique", "type": "workable", "slug": ["trailofbits"]},
    {"company": "Trail of Bits (careers page)", "group": "boutique", "type": "page_scan",
     "url": ["https://www.trailofbits.com/careers", "https://jobs.trailofbits.com/"]},
    {"company": "Doyensec", "group": "boutique", "type": "page_scan", "url": ["https://doyensec.com/careers.html"]},
    {"company": "NCC Group", "group": "boutique", "type": "workday", "host": "nccgroup.wd3.myworkdayjobs.com",
     "tenant": "nccgroup", "site": ["NCC_Group_Careers", "NCCGroup", "External", "NCC_Group"], "queries": ["intern", "graduate"]},
    {"company": "NCC Group (careers page)", "group": "boutique", "type": "page_scan",
     "url": ["https://www.nccgroup.com/us/careers/", "https://www.nccgroup.com/uk/careers/"]},
    {"company": "Include Security", "group": "boutique", "type": "page_scan", "url": ["https://includesecurity.com/careers/", "https://includesecurity.com/"]},
    {"company": "X41 D-Sec", "group": "boutique", "type": "page_scan", "url": ["https://x41-dsec.de/jobs/"]},
    {"company": "Atredis Partners", "group": "boutique", "type": "page_scan", "url": ["https://www.atredis.com/careers", "https://www.atredis.com/"]},
    {"company": "ForAllSecure / Mayhem", "group": "boutique", "type": "page_scan", "url": ["https://mayhem.security/careers"]},
    {"company": "GRIMM", "group": "boutique", "type": "page_scan", "url": ["https://www.grimmcyber.com/careers"]},
    {"company": "FuzzingLabs", "group": "boutique", "type": "page_scan", "url": ["https://fuzzinglabs.com/careers/", "https://fuzzinglabs.com/jobs/"]},
    {"company": "Kudelski Security", "group": "boutique", "type": "page_scan", "url": ["https://careers.kudelskisecurity.com/"]},
    {"company": "Bishop Fox", "group": "boutique", "type": "greenhouse", "slug": ["bishopfox"]},
    {"company": "Praetorian", "group": "boutique", "type": "greenhouse", "slug": ["praetorian"]},
    {"company": "Cure53", "group": "boutique", "type": "page_scan", "url": ["https://cure53.de/"]},
    {"company": "Synacktiv", "group": "boutique", "type": "page_scan", "url": ["https://www.synacktiv.com/en/offers", "https://www.synacktiv.com/offres", "https://www.synacktiv.com/en"]},
    {"company": "Quarkslab", "group": "boutique", "type": "page_scan", "url": ["https://www.quarkslab.com/jobs/", "https://www.quarkslab.com/join-us/", "https://www.quarkslab.com/"]},
    {"company": "SEC Consult", "group": "boutique", "type": "page_scan", "url": ["https://sec-consult.com/career/"]},
    {"company": "ERNW", "group": "boutique", "type": "page_scan", "url": ["https://ernw.de/en/jobs.html", "https://ernw.de/en/company/jobs.html", "https://www.ernw.de/en/career.html"]},
    {"company": "NVISO", "group": "boutique", "type": "page_scan", "url": ["https://www.nviso.eu/en/jobs", "https://www.nviso.eu/jobs", "https://www.nviso.eu/"]},
        {"company": "Zellic", "group": "boutique", "type": "ats_any", "candidates": [{"type": "greenhouse", "slug": "zellic"}, {"type": "lever", "slug": "zellic"}, {"type": "ashby", "slug": "zellic"}]},
    {"company": "OtterSec", "group": "boutique", "type": "page_scan", "url": ["https://osec.io/careers", "https://osec.io/"]},
    {"company": "Immunefi", "group": "boutique", "type": "greenhouse", "slug": ["immunefi"]},
    {"company": "HackerOne", "group": "boutique", "type": "ats_any", "candidates": [{"type": "lever", "slug": "hackerone"}, {"type": "ashby", "slug": "hackerone"}, {"type": "greenhouse", "slug": "hackerone"}]},
    {"company": "Semgrep", "group": "boutique", "type": "ashby", "slug": ["semgrep"]},
    {"company": "Snyk", "group": "boutique", "type": "ats_any", "candidates": [{"type": "lever", "slug": "snyk"}, {"type": "ashby", "slug": "snyk"}, {"type": "greenhouse", "slug": "snyk"}]},
    {"company": "Wiz", "group": "boutique", "type": "greenhouse", "slug": ["wizinc", "wiz"]},
    {"company": "CrowdStrike", "group": "boutique", "type": "workday", "host": "crowdstrike.wd5.myworkdayjobs.com",
     "tenant": "crowdstrike", "site": ["crowdstrikecareers"], "queries": ["intern"]},
    {"company": "SentinelOne", "group": "boutique", "type": "greenhouse", "slug": ["sentinelone", "sentinellabs"]},
    {"company": "Rapid7", "group": "boutique", "type": "page_scan", "url": ["https://careers.rapid7.com/jobs/search?query=intern", "https://careers.rapid7.com/"]},
    {"company": "Tenable", "group": "boutique", "type": "greenhouse", "slug": ["tenable", "tenableinc"]},
    {"company": "Palo Alto Networks", "group": "boutique", "type": "page_scan",
     "url": ["https://jobs.paloaltonetworks.com/en/jobs/?search=intern", "https://jobs.paloaltonetworks.com/students"]},
    {"company": "Zscaler", "group": "boutique", "type": "smartrecruiters", "slug": ["Zscaler"], "queries": ["intern"]},
    {"company": "Fortinet", "group": "boutique", "type": "workday", "host": "fortinet.wd3.myworkdayjobs.com",
     "tenant": "fortinet", "site": [], "queries": ["intern"]},
    {"company": "Sophos", "group": "boutique", "type": "workday", "host": "sophos.wd1.myworkdayjobs.com",
     "tenant": "sophos", "site": [], "queries": ["intern"]},
    {"company": "Check Point", "group": "boutique", "type": "page_scan", "url": ["https://careers.checkpoint.com/index.php?m=jobs", "https://careers.checkpoint.com/"]},
    {"company": "ESET", "group": "boutique", "type": "page_scan", "url": ["https://www.eset.com/int/about/careers/"]},
    {"company": "Mandiant / Google Cloud Security", "group": "boutique", "type": "page_scan",
     "url": ["https://www.google.com/about/careers/applications/jobs/results?q=mandiant%20intern"]},
    {"company": "Cyberhaven", "group": "boutique", "type": "ats_any", "candidates": [{"type": "ashby", "slug": "cyberhaven"}, {"type": "lever", "slug": "cyberhaven"}, {"type": "greenhouse", "slug": "cyberhaven"}]},
    {"company": "Tailscale", "group": "boutique", "type": "greenhouse", "slug": ["tailscale"]},
    {"company": "Vercel", "group": "boutique", "type": "greenhouse", "slug": ["vercel"]},

    # --------------------------------------------------------- Banks / finance
    {"company": "JPMorgan Chase", "group": "bank", "type": "oracle_hcm", "host": "jpmc.fa.oraclecloud.com",
     "site": "CX_1001", "queries": ["intern", "cybersecurity", "summer analyst"]},
    {"company": "Morgan Stanley", "group": "bank", "type": "page_scan", "url": ["https://www.morganstanley.com/careers/students-graduates", "https://morganstanley.eightfold.ai/careers?query=intern"]},
    {"company": "Goldman Sachs", "group": "bank", "type": "page_scan",
     "url": ["https://higher.gs.com/roles?division=Engineering", "https://www.goldmansachs.com/careers/students"]},
    {"company": "Citi", "group": "bank", "type": "workday", "host": "citi.wd5.myworkdayjobs.com",
     "tenant": "citi", "site": ["2", "Citi", "External"], "queries": ["intern", "summer analyst"]},
    {"company": "Capital One", "group": "bank", "type": "workday", "host": "capitalone.wd12.myworkdayjobs.com",
     "tenant": "capitalone", "site": ["Capital_One", "External"], "queries": ["intern"]},
    {"company": "HSBC", "group": "bank", "type": "workday", "host": "hsbc.wd3.myworkdayjobs.com",
     "tenant": "hsbc", "site": [], "queries": ["intern"]},
    {"company": "Barclays", "group": "bank", "type": "page_scan", "url": ["https://search.jobs.barclays/search-jobs?k=intern"]},
    {"company": "Deutsche Bank", "group": "bank", "type": "page_scan", "url": ["https://careers.db.com/students-graduates/"]},
    {"company": "UBS", "group": "bank", "type": "page_scan", "url": ["https://www.ubs.com/global/en/careers/students-graduates.html", "https://jobs.ubs.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=25008&siteid=5131&PageType=searchResults&SearchType=linkquery&LinkID=6"]},
    {"company": "Intesa Sanpaolo", "group": "bank", "type": "page_scan", "url": ["https://jobs.intesasanpaolo.com/"]},
    {"company": "UniCredit", "group": "bank", "type": "page_scan", "url": ["https://www.unicreditgroup.eu/en/careers.html"]},
    {"company": "Bloomberg", "group": "bank", "type": "page_scan", "url": ["https://careers.bloomberg.com/job/search?qc=Internship", "https://www.bloomberg.com/company/careers/early-career/"]},
    {"company": "Jane Street", "group": "bank", "type": "page_scan", "url": ["https://www.janestreet.com/join-jane-street/open-roles/"]},
    {"company": "Two Sigma", "group": "bank", "type": "ats_any", "candidates": [{"type": "greenhouse", "slug": "twosigmainvestments"}, {"type": "lever", "slug": "twosigma"}, {"type": "ashby", "slug": "twosigma"}]},
    {"company": "Hudson River Trading", "group": "bank", "type": "greenhouse", "slug": ["wehrtyou", "hudsonrivertrading"]},
    {"company": "Citadel", "group": "bank", "type": "page_scan", "url": ["https://www.citadel.com/careers/students-and-new-grads/", "https://www.citadel.com/careers/open-opportunities/"]},
    {"company": "DRW", "group": "bank", "type": "greenhouse", "slug": ["drweng", "drw"]},
    {"company": "IMC Trading", "group": "bank", "type": "greenhouse", "slug": ["imc"]},
    {"company": "Optiver", "group": "bank", "type": "greenhouse", "slug": ["optiverus", "optiver"]},
    {"company": "Wise", "group": "bank", "type": "greenhouse", "slug": ["transferwise", "wise"]},
    {"company": "Revolut", "group": "bank", "type": "page_scan", "url": ["https://www.revolut.com/careers/"]},

    # --------------------------------------------------------- Academic labs
    {"company": "CISPA", "group": "academic", "type": "page_scan", "url": ["https://career.cispa.de/internship", "https://cispa.de/en/career"]},
    {"company": "Max Planck (CIS)", "group": "academic", "type": "page_scan", "url": ["https://www.cis.mpg.de/internships/"]},
    {"company": "MPI-SP", "group": "academic", "type": "page_scan", "url": ["https://www.mpi-sp.org/career", "https://www.mpi-sp.org/"]},
    {"company": "ETH Zurich (D-INFK)", "group": "academic", "type": "page_scan",
     "url": ["https://inf.ethz.ch/studies/summer-research-fellowship.html"]},
    {"company": "EPFL", "group": "academic", "type": "page_scan", "url": ["https://summer.epfl.ch/", "https://www.epfl.ch/schools/ic/education/internships/"]},
    ]
